spring:
  data.mongodb:
    host: localhost
    password: example
    port: 27018
    username: root
    database: local
    authentication-database: admin
logging.level.org.springframework.data.mongodb: DEBUG
