spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Example

logging.level:
#  org.springframework.boot.autoconfigure.security: TRACE
  org.springframework.security: DEBUG
  org.springframework.web: INFO
server:
  port: 8081
