version: '3.7'

services:

  db:
    image: postgres:10.0
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
