version: "3.0"
services:
  mongo:
    image: mongo:4.4.5-bionic
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

