CREATE TABLE TEST_ENTITY
(
    ID        BIGSERIAL NOT NULL,
    CHARACTER VARCHAR(3),
    NUMERIC   NUMERIC(7),
    DATETIME  DATE,
    CONSTRAINT PK_TEST_ENTITY
        PRIMARY KEY (ID)
);

CREATE INDEX CI_TEST_ENTITY
    ON TEST_ENTITY (ID);
