CREATE TABLE TEST_ENTITY
(
    ID        BIGSERIAL NOT NULL,
    CHARACTER VARCHAR(3),
    NUMERIC   NUMERIC(7),
    DATETIME  DATE,
    CONSTRAINT PK_TEST_ENTITY
        PRIMARY KEY (ID)
);

CREATE INDEX CI_TEST_ENTITY
    ON TEST_ENTITY (ID);

ALTER SEQUENCE IF EXISTS test_entity_id_seq INCREMENT 50;

CREATE TABLE TEST_ENTITY_2
(
    ID        BIGSERIAL NOT NULL,
    CHARACTER VARCHAR(6),
    NUMERIC   NUMERIC(7),
    DATETIME  DATE,
    CONSTRAINT PK_TEST_ENTITY_2
        PRIMARY KEY (ID)
);

CREATE INDEX CI_TEST_ENTITY_2
    ON TEST_ENTITY_2 (ID);

ALTER SEQUENCE IF EXISTS test_entity_2_id_seq INCREMENT 50;
