version: '3.7'

services:

  db-postgresql:
    image: jpa-exploration-postgresql
    build:
      context:
        docker/postgresql/
    ports:
      - "5432:5432"
    expose:
      - "5432"

  db-mssql:
    image: jpa-exploration-mssql
    build:
      context:
        docker/mssql/
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password1
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose:
      - "1433"

networks:
  default:
    name: jpa-exploration-network