camunda:
  bpm:
    webapp:
    #  index-redirect-enabled: false
    admin-user:
      id: admin
      password: secret
      firstName: Admin
    #filter:
    #  create: All tasks
    metrics:
      enabled: true