USE jpa_exploration;

CREATE TABLE TEST_ENTITY
(
    ID        INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    CHARACTER CHAR(3),
    NUMERIC   NUMERIC(7),
    DATETIME  DATETIME,
)
GO

CREATE index CI_TEST_ENTITY
    ON TEST_ENTITY (ID)
GO
